# Generated by Django 4.1 on 2022-10-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleadoslc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadoslc',
            name='salariobase',
            field=models.FloatField(default=130, verbose_name='Salario Base'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalempleadoslc',
            name='salariobase',
            field=models.FloatField(default=2, verbose_name='Salario Base'),
            preserve_default=False,
        ),
    ]
